namespace XenaUI.Utils
{
    public class RequestCommonData : Data
    {
        /// <summary>
        /// IdSalesOrder
        /// </summary>
        public string IdSalesOrder { get; set; }

        /// <summary>
        /// IdPerson
        /// </summary>
        public string IdPerson { get; set; }

        /// <summary>
        /// ListOfIdMandants
        /// </summary>
        public string ListOfIdMandants { get; set; }

        /// <summary>
        /// IdRepWidgetApp
        /// </summary>
        public string IdRepWidgetApp { get; set; }

        /// <summary>
        /// IdBackOfficeLetters
        /// </summary>
        public string IdBackOfficeLetters { get; set; }
    }
    public class ConfirmBackOfficeLettersData : Data 
    {
        private string jSONSalesOrderLetters = null;
        /// <summary>
        /// jSONSalesOrderLetters
        /// </summary>
        public string JSONSalesOrderLetters { get { return jSONSalesOrderLetters; } set { if (!string.IsNullOrEmpty(value)) jSONSalesOrderLetters = value; } }
    }

    public class BackOfficeLettersData : Data
    {        
        /// <summary>
        /// IdSalesOrderLetters
        /// </summary>
        public string IdSalesOrderLetters { get; set; }

        /// <summary>
        /// IdBackOfficeLetters
        /// </summary>
        public string IdBackOfficeLetters { get; set; }

        /// <summary>
        /// IdGenerateLetter
        /// </summary>
        public string IdGenerateLetter { get; set; }

        /// <summary>
        /// IdSalesOrder
        /// </summary>
        public string IdSalesOrder { get; set; }

        /// <summary>
        /// IdPerson
        /// </summary>
        public string IdPerson { get; set; }

        /// <summary>
        /// IsSoftDelete
        /// </summary>
        public string IsSoftDelete { get; set; }

        /// <summary>
        /// IsDeleted
        /// </summary>
        public string IsDeleted { get; set; }

        /// <summary>
        /// IsActive
        /// </summary>
        public string IsActive { get; set; }

        /// <summary>
        /// Notes
        /// </summary>
        public string Notes { get; set; }

        private string jSONGenerateLetterItems = null;
        /// <summary>
        /// JSONGenerateLetterItems
        /// </summary>
        public string JSONGenerateLetterItems { get { return jSONGenerateLetterItems; } set { if (!string.IsNullOrEmpty(value)) jSONGenerateLetterItems = value; } }

        private string jSONBackOfficeLettersTest = null;
        /// <summary>
        /// JSONBackOfficeLettersTest
        /// </summary>
        public string JSONBackOfficeLettersTest { get { return jSONBackOfficeLettersTest; } set { if (!string.IsNullOrEmpty(value)) jSONBackOfficeLettersTest = value; } }

        private string jSONTreeMedia = null;
        /// <summary>
        /// JSONTreeMedia
        /// </summary>
        public string JSONTreeMedia { get { return jSONTreeMedia; } set { if (!string.IsNullOrEmpty(value)) jSONTreeMedia = value; } }
    }

    public class BackOfficeLetterTemplateData : Data
    { /// <summary>
      /// LetterName
      /// </summary>
        public string LetterName { get; set; }

        /// <summary>
        /// IsActive
        /// </summary>
        public string IsActive { get; set; }

        /// <summary>
        /// IdBackOfficeLetters
        /// </summary>
        public string IdBackOfficeLetters { get; set; }

        /// <summary>
        /// IsAutoGeneratedLetter
        /// </summary>
        public string IsAutoGeneratedLetter { get; set; }

        /// <summary>
        /// IdRepTypeOfAutoLetter
        /// </summary>
        public string IdRepTypeOfAutoLetter { get; set; }

        /// <summary>
        /// IsSoftDelete
        /// </summary>
        public string IsSoftDelete { get; set; }

        /// <summary>
        /// IsDeleted
        /// </summary>
        public string IsDeleted { get; set; }

        /// <summary>
        /// JSONMandant
        /// </summary>
        public string JSONMandant { get; set; }

        /// <summary>
        /// JSONCountries
        /// </summary>
        public string JSONCountries { get; set; }

        /// <summary>
        /// JSONAssignWidget
        /// </summary>
        public string JSONAssignWidget { get; set; }

        /// <summary>
        /// JSONGroupsAndItems
        /// </summary>
        public string JSONGroupsAndItems { get; set; }

        /// <summary>
        /// JSONWordDocTemplate
        /// </summary>
        public string JSONWordDocTemplate { get; set; }
    }

    public class BackOfficeLetterTemplateDeleteData : Data
    {
        public string IdGenerateLetter { get; set; }
    }
        
}
